apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "leaf-php-chart.fullname" . }}-nginx-config
  labels:
    {{- include "leaf-php-chart.labels" . | nindent 4 }}
data:
  default.conf: |
    server {
        listen 80 default_server;
        server_name _;
        root /var/www/html;
        index index.php;

        location / {
            try_files $uri $uri/ /index.php?$query_string;
        }

        location ~ \.php$ {
            fastcgi_pass localhost:9000;
            fastcgi_index index.php;
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
            include fastcgi_params;
        }

        # Deny access to . files
        location ~ /\. {
            deny all;
        }

        # Deny access to default nginx welcome page
        location = /index.html {
            return 404;
        }
    } 